### ISSUE TITLE
Warp route deployment should be able to handle multiple collaterals

### ISSUE THREAD

**Issue by ltyu** [hyperlane-xyz/hyperlane-monorepo#3666]
## Problem
Currently, the CLI cannot handle a config with multiple collaterals on different chains. For example,
```
arbitrum:
  type: native
  address: "0x0000000000000000000000000000000000000000"
  isNft: false
polygon:
  type: native
  address: "0x0000000000000000000000000000000000000000"
  isNft: false
zksync:
  type: synthetic
```
This is due to `runBuildConfigStep()` of [warp.ts](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/f8b6ea467a169044257fb1247688b55ea6dbc78f/typescript/cli/src/deploy/warp.ts#L168-L169) overwriting `baseChainName` and `baseMetadata` for multiple collaterals.  These variables are then passed downstream to be used in [deploy plan](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/f8b6ea467a169044257fb1247688b55ea6dbc78f/typescript/cli/src/deploy/warp.ts#L261) and [dryrun](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/f8b6ea467a169044257fb1247688b55ea6dbc78f/typescript/cli/src/deploy/warp.ts#L296-L298). 

Also, `buildTokenMetadata()` of [HypERC20/HypERC721Deployer](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/f8b6ea467a169044257fb1247688b55ea6dbc78f/typescript/sdk/src/token/deploy.ts#L217-L247) is [duplicated in the CLI](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/f8b6ea467a169044257fb1247688b55ea6dbc78f/typescript/cli/src/deploy/warp.ts#L185-L203).

## Solution
- Consider removing, or redefining the dependency on `baseChainName` and `baseMetadata` in the downstream functions (deploy plan, dry-run, etc.). For synthetic tokens, we can simply rely on `baseMetadata` as it is expected that all collaterals will be the same.
- Remove `HyERC20/ERC721.buildTokenMetadata()` and move any extra logic to the CLI

## Nice to Have
- Allow the user to pick the synthetic token's metadata if there are multiple collateral instead of relying on the last `baseMetadata`
