### ISSUE TITLE
Hyperlane Warp Deploy not creating file with correct symbol

### ISSUE THREAD

**Issue by Xaroz** [hyperlane-xyz/hyperlane-monorepo#5164]
## Problem

**Is your feature request related to a problem? Please describe.**
When running `hyperlane warp deploy` where the resulting synthetic token symbol is different from the collateral one, it will spit out a `.config-yaml `file that does not contain the correct symbol, but the resulting token is still correct

**Additional context**

Issue happened when trying to do `hyperlane warp deploy` from `base USDC` to `artela USDC.a`:
```typescript
export const getArtelaBaseUSDCWarpConfig = async (
  routerConfig: ChainMap<RouterConfigWithoutOwner>,
): Promise<ChainMap<HypTokenRouterConfig>> => {
  const artela: HypTokenRouterConfig = {
    ...routerConfig.artela,
    owner: artelaOwner,
    type: TokenType.synthetic,
    symbol: 'USDC.a',
    interchainSecurityModule: ISM_CONFIG,
  };

  const base: HypTokenRouterConfig = {
    ...routerConfig.base,
    owner: baseOwner,
    type: TokenType.collateral,
    token: tokens.base.USDC,
    interchainSecurityModule: ISM_CONFIG,
  };

  return {
    artela,
    base,
  };
};
```

After running the command it spits the following config.yaml file:
```yaml
tokens:
  - addressOrDenom: "0x8d9Bd7E9ec3cd799a659EE650DfF6C799309fA91"
    chainName: artela
    connections:
      - token: ethereum|base|0x01348F639D6e418A5a9673c08c0dDf6ecCB80F37
    decimals: 6
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0x01348F639D6e418A5a9673c08c0dDf6ecCB80F37"
    chainName: base
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|artela|0x8d9Bd7E9ec3cd799a659EE650DfF6C799309fA91
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
```
But if you check the contract itself, it will show that deploy was done correctly in the correct symbol: https://artscan.artela.network/token/0x8d9Bd7E9ec3cd799a659EE650DfF6C799309fA91

## Solution

**Describe the solution you'd like**
The `hyperlane warp deploy` command should spit a config file with the correct symbols

**Describe alternatives you've considered**

## Nice to Have

**Describe non-essential extensions to the solution**
Additional features which should be implemented if they are easy to accommodate but otherwise can be skipped
