### ISSUE TITLE
HookModule update cannot handle addresses

### ISSUE THREAD

**Issue by ltyu** [hyperlane-xyz/hyperlane-monorepo#5456]
## Context
Renzo specifies an aggregate of the defaultHook with their ProtocolFeel. The config specifies an address for the default hook.

```
hook:
    hooks:
      - "0x9e8fFb1c26099e75Dd5D794030e2E9AA51471c25"
      - beneficiary: "0x0e60fd361fF5b90088e1782e6b21A7D177d462C5"
        maxProtocolFee: "100000000000000000000"
        owner: "0x0e60fd361fF5b90088e1782e6b21A7D177d462C5"
        protocolFee: "158365200000000"
        type: protocolFee
    type: aggregationHook
```

## Problem
When running warp apply and subsequently HookModule.update(), the Module attempts to redeploy the hook, despite no changes. This is due to the defaultHook address being compared to the derived version of it. 

## Solution
- Consider adding a short circuit such that if a hook address is supplied, derive it to compare
- Alternatively, compare the address to the actual address
